### ISSUE TITLE
YouTube links need updating (again)

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/text_principles-of-marketing-v2.0#2]
The link style `http://www.youtube.com/v/ZNfqKHSkL7o` no longer works. Specifically, the `/v/` causes the browser to attempt to download a file named with the last part of the URL.

The `/v/` should be changed to `/watch?v=`

So:
`http://www.youtube.com/v/ZNfqKHSkL7o`

becomes:
`http://www.youtube.com/watch?v=ZNfqKHSkL7o`

**Comment by athuggins** [comment]
Thanks for the heads-up; I had the same problem with another book. These should be fixed now.
